name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Gradle
      run: |
        ./gradlew assemblePrerelease build androidSourcesJar
        ./gradlew makeJar # for classes.jar, has to be done after assemblePrerelease
      env:
        SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}

    - name: arm64
      uses: actions/upload-artifact@v4
      with:
        name: Arm64
        path: ${{ github.workspace }}/app/build/outputs/apk/prerelease/release/*arm64-v8a.apk

    - name: armeabi-v7a
      uses: actions/upload-artifact@v4
      with:
        name: Armeabi-v7a
        path: ${{ github.workspace }}/app/build/outputs/apk/prerelease/release/*armeabi-v7a.apk

    - name: x86
      uses: actions/upload-artifact@v4
      with:
        name: X86
        path: ${{ github.workspace }}/app/build/outputs/apk/prerelease/release/*x86.apk

    - name: x86_64
      uses: actions/upload-artifact@v4
      with:
        name: X86_64
        path: ${{ github.workspace }}/app/build/outputs/apk/prerelease/release/*x86_64.apk

    - name: universal
      uses: actions/upload-artifact@v4
      with:
        name: Universal
        path: ${{ github.workspace }}/app/build/outputs/apk/prerelease/release/*universal.apk
